[tool.poetry]
name = "temporal"
version = "0.1.0"
description = ""
authors = ["Rafal Niewinski"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
